### ISSUE TITLE
[biocterm] [dev] [WIP] Biocterm backend

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocTerm#1]
# [biocterm] [dev] [WIP] Develop Custom Tmux Plugin

# Tasks 
- [ ] create output log 
https://github.com/tmux-plugins/tmux-logging
- [ ] session loading/restoration and lesson progress log + metadata
https://github.com/tmux-plugins/tmux-continuum
https://github.com/tmux-plugins/tmux-resurrect

- [ ] config pointers + file structure for contained installation
https://github.com/tmux-plugins/tpm/blob/master/docs/changing_plugins_install_dir.md

- [ ] bash scripting for: install, r-vim, bash-r communication config, pulling system data, .ini files

# Resources

tmux plugin manager: https://github.com/tmux-plugins/tpm

[other usability] 
https://github.com/tmux-plugins/tmux-pain-control
https://github.com/tmux-plugins/tmux-yank

---
# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
