### ISSUE TITLE
[BiocTerm][dev][WIP] Create multilanguage interactive course environment  

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocTerm#8]
# [BiocTerm][dev][WIP] Create multilanguage interactive course environment  

# Tasks 
- [x] Write basic course YAML template(s)
- [x] Write Bash Scripts that read in YAML values as variables and overwrite the YAML values 
        * yq for reading/writing and bash-yaml for creating environment variables
        * libyaml also exists for c
- [ ] Use demo magic to distinguish between background and foreground commands and what is displayed in terminal, make compatible with different languages 
- [ ] Take userinput and pass onto "Smart Checker" 

**// DEV NOTE: I am thinking of using golang above C/C++ and Python. Will update shortly with a complete redo of this issue**

# Resources
(Parse YAML using bash)
https://gist.github.com/pkuczynski/8665367
https://github.com/0k/shyaml
https://github.com/jasperes/bash-yaml
https://github.com/yaml/libyaml

https://starkandwayne.com/blog/bashing-your-yaml/
https://github.com/mikefarah/yq
https://stackoverflow.com/questions/29969527/linux-shell-get-value-of-a-field-from-a-yml-file

(Course displaying) 
https://github.com/paxtonhare/demo-magic

(Taking user input) 
https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_08_02.html

(Embedding other languages inside bash) 
https://www.linux.org/threads/embedding-other-languages-in-bash-scripts.8690/

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
